### ISSUE TITLE
favicon.ico cannot be loaded

### ISSUE THREAD

**Issue by erdoganpak** [utdemir/utdemir.com#2]
I got this error while trying to get favicon.ico

Failed to load resource: the server responded with a status of 404 (Not Found)

Is it a file missing or intended?

**Comment by utdemir** [comment]
Hey.

My website doesn't use a favicon, but some browsers (Chrome, IE and Safari, but not Firefox) requests that file regardless of sites HTML.

So, it's both a file missing and intended.

But if you find a simple and good looking 32x32 icon describing me, please suggest :).

**Comment by erdoganpak** [comment]
Here you go; 
[utdemir.zip](https://github.com/utdemir/utdemir.com/files/108702/utdemir.zip)
:)

**Comment by utdemir** [comment]
@erdoganpak IMO It's not very clear, and I don't want to look like *that* egoistic. It should be something recognisable.
